#pragma config(Motor,  port1,           LeftDrive,     tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           RightDrive,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           TopLift,       tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           BottomLift,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           BallLift,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           Flywheel01,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           Flywheel02,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           LeftClaw,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           RightClaw,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,           ,             tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*---------------------------------------------------------------------------*/
/*        Description: Competition template for VEX EDR                      */
/*---------------------------------------------------------------------------*/
#pragma platform(VEX2)
#pragma competitionControl(Competition)
#include "Vex_Competition_Includes.c"
/*---------------------------------------------------------------------------*/
/*                          Pre-Autonomous Functions                         */
/*  You may want to perform some actions before the competition starts.      */
/*  Do them in the following function.  You must return from this function   */
/*  or the autonomous and usercontrol tasks will not be started.  This       */
/*  function is only called once after the cortex has been powered on and    */
/*  not every time that the robot is disabled.                               */
/*---------------------------------------------------------------------------*/
void pre_auton()
{
  // Set bStopTasksBetweenModes to false if you want to keep user created tasks
  // running between Autonomous and Driver controlled modes. You will need to
  // manage all user created tasks if set to false.
  bStopTasksBetweenModes = true;
	// Set bDisplayCompetitionStatusOnLcd to false if you don't want the LCD
	// used by the competition include file, for example, you might want
	// to display your team name on the LCD in this function.
	// bDisplayCompetitionStatusOnLcd = false;
  // All activities that occur before the competition starts
  // Example: clearing encoders, setting servo positions, ...
}

/*---------------------------------------------------------------------------*/
/*                              Autonomous Task                              */
/*  This task is used to control your robot during the autonomous phase of   */
/*  a VEX Competition.                                                       */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task autonomous()
{
  AutonomousCodePlaceholderForTesting();
}

/*---------------------------------------------------------------------------*/
/*                              User Control Task                            */
/*  This task is used to control your robot during the user control phase of */
/*  a VEX Competition.                                                       */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task usercontrol()
{

  while (true)
  {
    motor[LeftDrive] = (vexRT[Ch3] + vexRt[Ch4])/2; 	//Controls Drive on Left Joystick
		motor[RightDrive] = (vexRT[Ch3] - vexRT[Ch4])/2;


		if(vexRT[Btn5U] == 1){														//Controls Claw Arms
			motor[LeftClaw] = 127;													//Using Button 5 Upper
			motor[RightClaw] = 127;													//and Down
		}
		else if(vexRt[Btn5D] == 1){
			motor[LeftClaw] = -127;
			motor[RightClaw] = -127;
		}
		else{
			motor[LeftClaw] = 0;
			motor[RightClaw] = 0;
		}



		if(vexRT[Btn6U] == 1){														//Controls the Flywheel
			motor[BallLift] = 127;													//Using Button 6 Upper
			motor[Flywheel01] = 127;
			motor[Flywheel02] = 127;
		}

		else{
			while(motor[BallLift] != 0){										//Prevents the Motor From
					motor[BallLift] = motor[BallLift] - 20;			//Burning Out. Slowly Reduces
					motor[Flywheel01] = motor[Flywheel01] - 20;	//Speed.
					motor[Flywheel02] = motor[Flywheel02] - 20;
					wait1Msec(100);
				}

			motor[Balllift] = 0;
			motor[Flywheel01] = 0;
			motor[Flywheel02] = 0;
		}


		if(vexRt[Btn7U] == 1){														//Controls Lift Using Button
			motor[TopLift] = 	127;													//7 Upper and Down
			motor[BottomLift] = 127;
		}

		else{
			motor[TopLift] = 0;
			motor[BottomLift] = 0;
		}

		if(vexRT[Btn8R] == 1){														//Emote
			motor[TopLift] = 127;
			motor[BottomLift] = 127;
			wait1Msec(6000);
			motor[TopLift] = 0;
			motor[BottomLift] = 0;

			motor[LeftDrive] = 127;
			wwait1Msec(3000);
			motor[LeftDrive] = 0;
		}


  }
}
